version: "3.7"
services:
    app:
        build: .
        restart: always
        networks: 
          - mynetwork 

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        depends_on:
            - app  
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
            - APP_HOST=app
            - APP_PORT=3000  
        networks:
          - mynetwork 
networks:
    mynetwork: 
        driver: bridge 
